# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='main.proto',
  package='Main',
  serialized_pb='\n\nmain.proto\x12\x04Main\"\x1e\n\x05Login\x12\x15\n\rclient_number\x18\x01 \x02(\x05\"\x1a\n\x08LoginAck\x12\x0e\n\x06result\x18\x01 \x02(\t\"\x14\n\x04Ping\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x05\"\x14\n\x04Pong\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\x05*A\n\x06IDEnum\x12\x0c\n\x08ID_Login\x10\x01\x12\x0f\n\x0bID_LoginAck\x10\x02\x12\x0b\n\x07ID_Ping\x10\x03\x12\x0b\n\x07ID_Pong\x10\x04')

_IDENUM = descriptor.EnumDescriptor(
  name='IDEnum',
  full_name='Main.IDEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='ID_Login', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ID_LoginAck', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ID_Ping', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ID_Pong', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=124,
  serialized_end=189,
)


ID_Login = 1
ID_LoginAck = 2
ID_Ping = 3
ID_Pong = 4



_LOGIN = descriptor.Descriptor(
  name='Login',
  full_name='Main.Login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='client_number', full_name='Main.Login.client_number', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=50,
)


_LOGINACK = descriptor.Descriptor(
  name='LoginAck',
  full_name='Main.LoginAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='Main.LoginAck.result', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=52,
  serialized_end=78,
)


_PING = descriptor.Descriptor(
  name='Ping',
  full_name='Main.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='Main.Ping.data', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=80,
  serialized_end=100,
)


_PONG = descriptor.Descriptor(
  name='Pong',
  full_name='Main.Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data', full_name='Main.Pong.data', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=102,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['Login'] = _LOGIN
DESCRIPTOR.message_types_by_name['LoginAck'] = _LOGINACK
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Pong'] = _PONG

class Login(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGIN
  
  # @@protoc_insertion_point(class_scope:Main.Login)

class LoginAck(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOGINACK
  
  # @@protoc_insertion_point(class_scope:Main.LoginAck)

class Ping(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PING
  
  # @@protoc_insertion_point(class_scope:Main.Ping)

class Pong(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PONG
  
  # @@protoc_insertion_point(class_scope:Main.Pong)

# @@protoc_insertion_point(module_scope)
