# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='main.proto',
  package='Main',
  syntax='proto3',
  serialized_pb=_b('\n\nmain.proto\x12\x04Main\"\x1e\n\x05Login\x12\x15\n\rclient_number\x18\x01 \x01(\x05\"\x1a\n\x08LoginAck\x12\x0e\n\x06result\x18\x01 \x01(\t\"\x14\n\x04Ping\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x05\"\x14\n\x04Pong\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x05*U\n\x06IDEnum\x12\x12\n\x0eID_PLACEHOLDER\x10\x00\x12\x0c\n\x08ID_Login\x10\x01\x12\x0f\n\x0bID_LoginAck\x10\x02\x12\x0b\n\x07ID_Ping\x10\x03\x12\x0b\n\x07ID_Pong\x10\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_IDENUM = _descriptor.EnumDescriptor(
  name='IDEnum',
  full_name='Main.IDEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID_PLACEHOLDER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ID_Login', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ID_LoginAck', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ID_Ping', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ID_Pong', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=124,
  serialized_end=209,
)
_sym_db.RegisterEnumDescriptor(_IDENUM)

IDEnum = enum_type_wrapper.EnumTypeWrapper(_IDENUM)
ID_PLACEHOLDER = 0
ID_Login = 1
ID_LoginAck = 2
ID_Ping = 3
ID_Pong = 4



_LOGIN = _descriptor.Descriptor(
  name='Login',
  full_name='Main.Login',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_number', full_name='Main.Login.client_number', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=50,
)


_LOGINACK = _descriptor.Descriptor(
  name='LoginAck',
  full_name='Main.LoginAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='Main.LoginAck.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=78,
)


_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='Main.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Main.Ping.data', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=100,
)


_PONG = _descriptor.Descriptor(
  name='Pong',
  full_name='Main.Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Main.Pong.data', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['Login'] = _LOGIN
DESCRIPTOR.message_types_by_name['LoginAck'] = _LOGINACK
DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
DESCRIPTOR.enum_types_by_name['IDEnum'] = _IDENUM

Login = _reflection.GeneratedProtocolMessageType('Login', (_message.Message,), dict(
  DESCRIPTOR = _LOGIN,
  __module__ = 'main_pb2'
  # @@protoc_insertion_point(class_scope:Main.Login)
  ))
_sym_db.RegisterMessage(Login)

LoginAck = _reflection.GeneratedProtocolMessageType('LoginAck', (_message.Message,), dict(
  DESCRIPTOR = _LOGINACK,
  __module__ = 'main_pb2'
  # @@protoc_insertion_point(class_scope:Main.LoginAck)
  ))
_sym_db.RegisterMessage(LoginAck)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
  DESCRIPTOR = _PING,
  __module__ = 'main_pb2'
  # @@protoc_insertion_point(class_scope:Main.Ping)
  ))
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), dict(
  DESCRIPTOR = _PONG,
  __module__ = 'main_pb2'
  # @@protoc_insertion_point(class_scope:Main.Pong)
  ))
_sym_db.RegisterMessage(Pong)


# @@protoc_insertion_point(module_scope)
